# Generated by Django 5.1.4 on 2025-01-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=11, unique=True)),
                ('tc', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesap_no', models.CharField(max_length=16, unique=True)),
                ('hesap_turu', models.CharField(choices=[('vadesiz', 'Vadesiz Hesap'), ('vadeli', 'Vadeli Hesap'), ('yatirim', 'Yatırım Hesabı')], max_length=10)),
                ('bakiye', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('acilis_tarihi', models.DateTimeField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesaplar', to='banka.musteri')),
            ],
        ),
    ]
