# Generated by Django 5.1.4 on 2025-01-11 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesaplar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Musteri',
        ),
    ]
