# Generated by Django 5.1.4 on 2025-01-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0004_alter_hesap_musteri_delete_musteri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hesap',
        ),
    ]
