# Generated by Django 5.1.4 on 2025-01-11 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banka', '0007_delete_hesap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesap_no', models.CharField(max_length=26, unique=True)),
                ('hesap_turu', models.CharField(choices=[('vadesiz', 'Vadesiz Hesap'), ('vadeli', 'Vadeli Hesap'), ('yatirim', 'Yatırım Hesabı')], max_length=10)),
                ('bakiye', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('acilis_tarihi', models.DateTimeField(auto_now_add=True)),
                ('iban', models.CharField(max_length=26, unique=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesaplar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
