# Generated by Django 5.1.4 on 2025-01-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hesap',
        ),
    ]
