# Generated by Django 5.1.4 on 2025-01-11 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='bakiye',
            field=models.CharField(default=0.0, max_length=10),
        ),
        migrations.CreateModel(
            name='ParaGonderme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alici_iban', models.CharField(max_length=34)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderen', to='banka.hesap')),
            ],
        ),
    ]
