# Generated by Django 5.1.4 on 2025-01-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0014_alter_hesap_bakiye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='bakiye',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
