# Generated by Django 5.1.4 on 2025-01-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0015_alter_hesap_bakiye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='tel',
            field=models.CharField(max_length=11),
        ),
    ]
