# Generated by Django 5.1.4 on 2025-01-11 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0016_alter_hesap_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Islem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('islem_tipi', models.CharField(choices=[('Gonderme', 'Para Gönderme'), ('Cekme', 'Para Çekme')], max_length=10)),
                ('tarih_ve_saat', models.DateTimeField(default=django.utils.timezone.now)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alınan_islemler', to='banka.hesap')),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_islemler', to='banka.hesap')),
            ],
        ),
    ]
